### ISSUE TITLE
Path Error

### ISSUE THREAD

**Issue by xptree** [DS3Lab/RosENet#1]
When running 
```
python -m RosENet -- preprocess test_dataset
```

The code raise the error such that
```
python2: can't open file '/home/hussein/Repositories/Own/rosetta/main/source/scripts/python/public/molfile_to_params.py'
```

It seems that the authors' path is hard-coded at
https://github.com/DS3Lab/RosENet/blob/27bee1a9867793d4c2d172e0afc21cdcd0b1e5de/RosENet/constants.py#L64-L65  

I wonder how to fix this problem.

Thanks.

**Comment by xptree** [comment]
It seems that the above problem can be fixed by downloading the rosetta source file manually and updating the `root` variable in `constant.py`.

**Comment by hhassan1** [comment]
Yes, exactly. Sorry about the confusion.
Rosetta must also be installed, the source code alone should not be enough as we use the binaries to run docking and minimization of the ligand structures.

I modified the `README.md` to make this dependency and the path in `constants.py` more explicit.

I will close this issue, please reopen if you think there is still something unclear about the setup.

Thank you.
