### ISSUE TITLE
About the affinity data of Astex Dataset

### ISSUE THREAD

**Issue by agave233** [DS3Lab/RosENet#15]
Hi,
Could you please share the affinity data for Astex Diverse Dataset?
Thank you!

**Comment by hhassan1** [comment]
Hi, here are all the Astex binding affinities in pKa units:
```
1hvy 6.170000076293945
1tt1 4.190000057220459
1hp0 6.699999809265137
1r55 6.800000190734863
1jd0 8.239999771118164
1sg0 7.46999979019165
1n2v 4.079999923706055
1u1c 5.369999885559082
1ygc 9.460000038146973
2bm2 7.820000171661377
1hq2 6.769999980926514
1m2z 7.21999979019165
1sqn 9.399999618530273
1of6 6.050000190734863
1t9b 6.900000095367432
1q4g 6.889999866485596
1j3j 8.010000228881836
1l2s 4.590000152587891
1mmv 7.239999771118164
1w2g 4.570000171661377
```

**Comment by agave233** [comment]
> Hi, here are all the Astex binding affinities in pKa units:
> 
> ```
> 1hvy 6.170000076293945
> 1tt1 4.190000057220459
> 1hp0 6.699999809265137
> 1r55 6.800000190734863
> 1jd0 8.239999771118164
> 1sg0 7.46999979019165
> 1n2v 4.079999923706055
> 1u1c 5.369999885559082
> 1ygc 9.460000038146973
> 2bm2 7.820000171661377
> 1hq2 6.769999980926514
> 1m2z 7.21999979019165
> 1sqn 9.399999618530273
> 1of6 6.050000190734863
> 1t9b 6.900000095367432
> 1q4g 6.889999866485596
> 1j3j 8.010000228881836
> 1l2s 4.590000152587891
> 1mmv 7.239999771118164
> 1w2g 4.570000171661377
> ```

Thanks a lot! By the way, I have downloaded this dataset in https://www.ccdc.cam.ac.uk/support-and-resources/downloads/. But I can not find the binding affinity values anywhere.  Could you please tell me where did you get the affinity data?

**Comment by hhassan1** [comment]
The binding affinities mentioned above have been extracted from [Hartshorn et al., Diverse, High-Quality Test Set for the Validation of Protein−Ligand Docking Performance](https://pubs.acs.org/doi/10.1021/jm061277y) page 9 (Journal of Medicinal Chemistry, 2007, Vol. 50, No. 4, page 734).

Note that the units were normalized to pKa to get the values above.

**Comment by agave233** [comment]
> The binding affinities mentioned above have been extracted from [Hartshorn et al., Diverse, High-Quality Test Set for the Validation of Protein−Ligand Docking Performance](https://pubs.acs.org/doi/10.1021/jm061277y) page 9 (Journal of Medicinal Chemistry, 2007, Vol. 50, No. 4, page 734).
> 
> Note that the units were normalized to pKa to get the values above.

Thanks, I found it. I noticed that the pKa value can be calculated by -logKd/Ka. Does this normalization method work for other measures(e.g., Km, IC50 and EC50)?

**Comment by hhassan1** [comment]
In general the values are very similar. There are some conceptual differences between pKa (pKi and pKd) vs IC50 and the likes. If I recall correctly, we tested the relevance of disaggregating the binding affinities by pKa and pKi or not, and the predictions of the network were practically the same.
