### ISSUE TITLE
Hi! I have some questions about the labels file

### ISSUE THREAD

**Issue by wanyueli321** [DS3Lab/RosENet#7]
Thanks for your good study, and I've learned a lot from your work.
Now I want to train the RosENet with the PDBbind dataset, but I have some questions about the generation of the labels file.  
The first question is that, in the README part, you said that "the labels file stores a line per PDB folder with the binding affinity assigned to it", however, in the test_dataset, the example is 10gs and its corresponding binding affinity is 1 in the labels file, but its actual binding affinity is 6.4, so is there any transform operation with it?
The second question is that, how can I get the labels file? Directly write the PDB folder name and its binding affinity into it?
Looking for your reply.

**Comment by BCornelsen** [comment]
Regarding the second question:
The predicted -logKd/Ki value are part of the index files (4th column in index/INDEX_general_PL_data.YYYY or index/INDEX_refined_data.YYYY). I exported the values to the labels file with `awk '{ print $1, $4}' index/INDEX_refined_data.2019 > labels`

**Comment by wanyueli321** [comment]
Hi, Bastian! Thanks for your reply, it helps me a lot. And I also meet a problem, that is that the when run `python3 -m RosENet -- preprocess test_dataset`, I can get some result files in the test_dataset (as shown in **the first and second image**), but when I run `python3 -m RosENet -- voxelize test_dataset`, I get the output as shown in **the third image**, but I don't get any voxelization results in the "_filter_exp_12_25" file. Have ever met this problem, and can you tell me where I was wrong? Thanks very much.
![2](https://user-images.githubusercontent.com/35324075/89363630-42929d80-d703-11ea-9196-5a2f20246581.PNG)
![3](https://user-images.githubusercontent.com/35324075/89363640-46bebb00-d703-11ea-9afd-e87b56ecf94b.PNG)
![4](https://user-images.githubusercontent.com/35324075/89363648-49b9ab80-d703-11ea-9b6c-d198cc2ac585.PNG)
